#!/usr/bin/env node
/* make_week_card.js · the link card, the image X shows under every record link
   Written 22 September 2026 for the 23 September upload, note 32.

   The card it replaces, share_2026-08-30_gold_4350.png, showed one held row
   from 30 August for three weeks, with the retired sign-off in its footer.
   This one is regenerated by the routine every Sunday and every Friday, from
   record.json only, so it can never show a row, a close or a count the page
   does not hold:
     rows open     the week's lines, what each holds, the last Friday close
     none open     the week last graded, each grade and its close
   and under both, the count, wrong rows included.

   Writes week_card.html and card_<named date>_<open|graded>.png at 1200 x 630,
   then points the live og:image line in index.html at the new file. The old
   card files stay in the folder; nothing links to them.

   Run after make_record_json.js:
     node make_record_json.js && node make_week_card.js && node make_record_json.js
   (the second make_record_json picks up nothing new; it is there so the
   routine can be run in one line in any order without a stale record.json).

   BRAND LAW. No em dashes, hashtags, exclamation marks, emoji, forecasting,
   or sign-off line. The footer is the address and nothing else. */
const fs = require("fs");
const path = require("path");
const rec = JSON.parse(fs.readFileSync(path.join(__dirname, "record.json"), "utf8"));
const MON = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const fmt = iso => { const [y, m, d] = iso.split("-"); return `${+d} ${MON[+m - 1]}`; };
const num = t => parseFloat(String(t).replace(/,/g, ""));
const order = { Gold: 0, Silver: 1, Platinum: 2 };
const t = rec.tally;
const closes = rec.closes || [];
if (!closes.length) { console.log("record.json has no closes; run make_record_json.js on a page with CLOSES"); process.exit(1); }

let rows = rec.rows.filter(r => r.grade === "pending"), mode = "open";
if (!rows.length) { const d = rec.rows.map(r => r.named).sort().pop(); rows = rec.rows.filter(r => r.named === d); mode = "graded"; }
rows.sort((a, b) => (order[a.metal] ?? 9) - (order[b.metal] ?? 9));
const named = rows[0].named;
const friday = (() => { const d = new Date(named + "T12:00:00Z"); let add = (5 - d.getUTCDay() + 7) % 7; if (add === 0) add = 7; d.setUTCDate(d.getUTCDate() + add); return d.toISOString().slice(0, 10); })();
const cEntry = mode === "graded" ? (closes.find(c => c.date === friday) || closes[closes.length - 1]) : closes[closes.length - 1];
const side = r => /\babove\b/i.test(r.kill || "") ? "over" : "under";

const C = { bg:"#141210", panel:"#1D1A16", rule:"#4A4238", ink:"#EFE8DC", ink3:"#CFC6B8", ink5:"#B8AE9E", ink6:"#8E8474",
            gold:"#CBA43C", pass:"#5FA57A", miss:"#D2764A", open:"#6BA3C7", notest:"#9C9282" };
const GC = { pass: C.pass, miss: C.miss, partial: C.miss, pending: C.open, notest: C.notest };
const GW = { pass: "Held", miss: "Wrong", partial: "Wrong", pending: "Open", notest: "Never reached" };
const esc = s => String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);

const cols = rows.map(r => {
  const lv = num(String(r.level).split("/")[0]), clTxt = cEntry[r.metal], cl = clTxt ? num(clTxt) : NaN;
  const room = side(r) === "under" ? cl - lv : lv - cl;
  const dec = r.metal === "Silver" ? 3 : 2;
  const f = v => Math.abs(v).toLocaleString("en-GB", { minimumFractionDigits: dec, maximumFractionDigits: dec });
  const col = GC[r.grade] || C.notest;
  const line2 = mode === "open" ? (side(r) === "under" ? "holds above" : "stays below") : GW[r.grade];
  const line3 = clTxt ? `close ${fmt(cEntry.date)} · ${esc(clTxt)}` : "";
  const line4 = mode === "open" && isFinite(room) ? `${f(room)} ${room >= 0 ? "of room" : "through"}`
    : r.grade === "notest" ? "never reached" : isFinite(room) ? `${room >= 0 ? "+" : "−"}${f(room)} ${room >= 0 ? "clear" : "through"}` : "";
  return `<div class="c" style="border-top-color:${col}"><div class="m">${esc(r.metal)}</div><div class="lv" style="color:${col}">${esc(r.level)}</div>
    <div class="l2" style="color:${mode === "open" ? C.ink5 : col}">${esc(line2)}</div><div class="l3">${line3}</div><div class="l4" style="color:${col}">${esc(line4)}</div></div>`;
}).join("");

const kicker = mode === "open"
  ? `This week · named ${fmt(named)} · graded on the ${fmt(friday)} close`
  : `Graded on the ${fmt(friday)} close · the next lines are named Sunday`;

/* Local copies of the two faces, used when the sandbox cannot reach Google
   Fonts; on any other machine the Google stylesheet loads first and wins. */
const LOCAL = "/home/claude/fonts";
const localFaces = fs.existsSync(LOCAL) ? `
@font-face{font-family:'IBM Plex Mono';font-weight:500;src:url(file://${LOCAL}/package/fonts/complete/woff2/IBMPlexMono-Medium.woff2)}
@font-face{font-family:'IBM Plex Mono';font-weight:600;src:url(file://${LOCAL}/package/fonts/complete/woff2/IBMPlexMono-SemiBold.woff2)}
@font-face{font-family:'Newsreader';font-weight:400;src:url(file://${LOCAL}/nr/package/files/newsreader-latin-400-normal.woff2)}` : "";

const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>The record, this week</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400&family=IBM+Plex+Mono:wght@500;600&display=swap" rel="stylesheet">
<style>${localFaces}
*{box-sizing:border-box;margin:0;padding:0}
html,body{width:1200px;height:630px;overflow:hidden}
body{background:${C.bg};background-image:radial-gradient(900px 380px at 78% -12%,rgba(203,164,60,.10),transparent 70%);color:${C.ink3};font-family:'IBM Plex Mono',monospace;font-variant-numeric:tabular-nums;padding:44px 60px 36px;display:flex;flex-direction:column}
.mast{display:flex;justify-content:space-between;align-items:baseline;padding-bottom:14px;border-bottom:1.5px solid ${C.ink}}
.mast b{font-size:15px;font-weight:600;letter-spacing:.3em;color:${C.ink}}
.mast span{font-size:12.5px;font-weight:500;letter-spacing:.18em;color:${C.ink5};text-transform:uppercase}
.k{font-size:13.5px;font-weight:600;letter-spacing:.18em;text-transform:uppercase;color:${C.gold};margin:30px 0 18px}
.cols{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;flex:1}
.c{background:${C.panel};border-radius:12px;border-top:4px solid;padding:20px 22px;display:flex;flex-direction:column;justify-content:center}
.m{font-size:13px;font-weight:600;letter-spacing:.2em;text-transform:uppercase;color:${C.ink}}
.lv{font-size:68px;font-weight:600;letter-spacing:-.03em;line-height:1.05;margin:10px 0 12px}
.l2{font-size:13px;font-weight:600;letter-spacing:.14em;text-transform:uppercase}
.l3{font-size:16px;color:${C.ink3};margin-top:16px}
.l4{font-size:17px;font-weight:600;margin-top:6px}
.count{display:flex;gap:30px;align-items:baseline;margin-top:22px;padding-top:16px;border-top:1px solid ${C.rule};font-size:13px;letter-spacing:.12em;text-transform:uppercase;color:${C.ink5}}
.count b{font-size:26px;letter-spacing:0;margin-right:8px}
.count .url{margin-left:auto;letter-spacing:.08em;text-transform:none;color:${C.ink6};font-size:13px}
</style></head><body>
<div class="mast"><b>THE SIMPLIFIER</b><span>Metals · the record</span></div>
<div class="k">${esc(kicker)}</div>
<div class="cols">${cols}</div>
<div class="count"><span><b style="color:${C.ink}">${t.resolved}</b>resolved</span><span><b style="color:${C.pass}">${t.held}</b>held</span><span><b style="color:${C.miss}">${t.wrong}</b>wrong, kept</span>${t.open ? `<span><b style="color:${C.open}">${t.open}</b>open</span>` : ""}<span class="url">thesimplifier7.github.io/record</span></div>
</body></html>`;

const base = `card_${named}_${mode}`;
fs.writeFileSync(path.join(__dirname, "week_card.html"), html);
console.log(`week_card.html written: ${mode}, named ${named}, close ${cEntry.date}, ${rows.length} rows`);

/* point the live og:image line at the new card; the commented history above it is not touched */
/* the record and the bank board both carry the week card, 22 Sep 2026 */
const re = /^<meta property="og:image" content="https:\/\/thesimplifier7\.github\.io\/record\/[^"]+">$/m;
for (const f of ["index.html", "targets.html"]) {
  const fp = path.join(__dirname, f);
  if (!fs.existsSync(fp)) continue;
  const src = fs.readFileSync(fp, "utf8");
  if (!re.test(src)) { console.log(`live og:image line not found in ${f}; not changed`); if (f === "index.html") process.exit(1); continue; }
  const next = src.replace(re, `<meta property="og:image" content="https://thesimplifier7.github.io/record/${base}.png">`);
  if (next !== src) { fs.writeFileSync(fp, next); console.log(`${f} og:image now ${base}.png`); }
}

(async () => {
  let chromium; try { ({ chromium } = require("playwright")); } catch (e) { console.log(`playwright not installed; render week_card.html to ${base}.png by hand at 1200 x 630.`); return; }
  const opts = fs.existsSync("/opt/pw-browsers/chromium") ? { executablePath: "/opt/pw-browsers/chromium" } : {};
  const b = await chromium.launch(opts);
  const p = await b.newPage({ viewport: { width: 1200, height: 630 }, deviceScaleFactor: 1 });
  await p.goto("file://" + path.join(__dirname, "week_card.html"), { waitUntil: "load" });
  try { await p.evaluate(() => document.fonts.ready); } catch (e) {}
  await p.waitForTimeout(300);
  await p.screenshot({ path: path.join(__dirname, base + ".png") });
  await b.close();
  console.log(`${base}.png written at 1200 x 630`);
})();
